# -*- coding: utf-8 -*-
"""AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NongQZH0Lc-QpbYMEyPySuybRYnAva3-
"""

!pip install twelvelabs
from twelvelabs import TwelveLabs
client = TwelveLabs(api_key="tlk_1D4DWDE37ATK1J2C5MWVD39ARCE1")

!python -m pip install requests
headers = {
    "x-api-key": "tlk_1D4DWDE37ATK1J2C5MWVD39ARCE1"
}
INDEXES_URL = f"{https://dashboard.twelvelabs.io/home}/indexes"

!pip install twelvelabs
from twelvelabs import TwelveLabs
client = TwelveLabs(api_key="tlk_1D4DWDE37ATK1J2C5MWVD39ARCE1")

headers = {
    "x-api-key": "tlk_1D4DWDE37ATK1J2C5MWVD39ARCE1"
}
INDEXES_URL = f"https://dashboard.twelvelabs.io/home/indexes"
response = requests.get(INDEXES_URL, headers=headers)
print(response.text)

!pip install twelvelabs
from twelvelabs import TwelveLabs
client = TwelveLabs(api_key="tlk_1D4DWDE37ATK1J2C5MWVD39ARCE1")

headers = {
    "x-api-key": "tlk_1D4DWDE37ATK1J2C5MWVD39ARCE1"
}
INDEXES_URL = f"https://dashboard.twelvelabs.io/home/indexes"

!python -m pip install requests
headers = {
    "x-api-key": "tlk_1D4DWDE37ATK1J2C5MWVD39ARCE1"
}

INDEXES_URL = f"https://dashboard.twelvelabs.io/home/indexes"

import requests



# Install the requests module
!pip install requests

# Import the requests module
import requests

# Define the INDEX_NAME and data variables
INDEX_NAME = "<memomind>"
data = {
    "engines": [
      {
        "engine_name": "marengo2.6",
        "engine_options":  ["visual", "conversation", "text_in_video", "logo"]
      }
    ],
    "index_name": INDEX_NAME,
}

# Set the INDEXES_URL and headers variables
INDEXES_URL = f"https://dashboard.twelvelabs.io/home/indexes"
headers = {
    "x-api-key": "tlk_1D4DWDE37ATK1J2C5MWVD39ARCE1"
}

# Send the POST request to create the index
response = requests.post(INDEXES_URL, headers=headers, json=data)

# Print the status code and response
print (f'Status code: {response.status_code}')
print (response.json())

if response.status_code == 405:
    print("Error: The server returned a 405 (Method Not Allowed) error.")
    print("Please check if you have the correct permissions to create an index.")
else:
    print(response.json())

import logging

logging.basicConfig(level=logging.DEBUG)

# ...

response = requests.post(INDEXES_URL, headers=headers, json=data)

from twelvelabs import TwelveLabs

client = TwelveLabs(api_key="tlk_1D4DWDE37ATK1J2C5MWVD39ARCE1")

engines = [
        {
          "name": "marengo2.6",
          "options": ["visual", "conversation", "text_in_video", "logo"]
        }
  ]

engines = [
        {
            "name": "pegasus1",
            "options": ["visual", "conversation"]
        }
    ]

engines = [
        {
            "name": "pegasus1",
            "options": ["visual", "conversation"]
        },
        {
          "name": "marengo2.6",
          "options": ["visual", "conversation", "text_in_video", "logo"]
        }
    ]

index = client.index.create(
    name="<YOUR_INDEX_NAME>",
    engines=engines,
    addons=["thumbnail"] # Optional
)
print(f"A new index has been created: id={index.id} name={index.name} engines={index.engines}")





from twelvelabs import TwelveLabs
from twelvelabs.models.task import Task

client = TwelveLabs(api_key="tlk_1D4DWDE37ATK1J2C5MWVD39ARCE1")

task = client.task.create(
  index_id="6652c2d127f0a43b740fd8bb",
  file="/content/WhatsApp Video 2024-05-26 at 10.44.25.mp4",
)
print(f"Task id={task.id}")

# Utility function to print the status of a video indexing task
def on_task_update(task: Task):
      print(f"  Status={task.status}")

task.wait_for_done(sleep_interval=5, callback=on_task_update)

if task.status != "ready":
  raise RuntimeError(f"Indexing failed with status {task.status}")
print(f"The unique identifer of your video is {task.video_id}.")

from twelvelabs import TwelveLabs

client = TwelveLabs(api_key="tlk_1D4DWDE37ATK1J2C5MWVD39ARCE1")

gist = client.generate.gist(
  video_id="6652c6b4d22b3a3c97bef629",
  types=["title","topic","hashtag"]
)
print(f"Title={gist.title}\nTopic={gist.topics}\nHashtags={gist.hashtags}")

from twelvelabs import TwelveLabs

client = TwelveLabs(api_key="tlk_1D4DWDE37ATK1J2C5MWVD39ARCE1")

res = client.generate.text(
  video_id="/content/WhatsApp Video 2024-05-26 at 10.44.25.mp4",
  prompt="I want to generate a description for my video with the following format: Title of the video, followed by a summary in 2-3 sentences, highlighting the main topics."
)
print(f"{res.data}")

# python -m pip install requests

import requests

# Construct the URL of the `/embed` endpoint
BASE_URL = "https://api.twelvelabs.io"
VERSION = "v1.2"
EMBED_URL = f"{BASE_URL}/{VERSION}/embed"

# Set the headers of the request
headers = {
    "x-api-key": "tlk_1D4DWDE37ATK1J2C5MWVD39ARCE1"
}

# Specify the body of the request
data = {
    "engine_name": "Marengo-retrieval-2.6",
    "text": "bollywood",
}

# Invoke the POST method of the `/embed` endpoint
response = requests.post(EMBED_URL, headers=headers, data=data)

# Print the status code and the response
print(f"Status Code: {response.status_code}")
print("Response:")
print(response.json())

# python -m pip install requests

import requests

# Construct the URL of the `/embed` endpoint
BASE_URL = "https://api.twelvelabs.io"
VERSION = "v1.2"
EMBED_URL = f"{BASE_URL}/{VERSION}/embed"

# Set the headers of the request
headers = {
    "x-api-key": "tlk_1D4DWDE37ATK1J2C5MWVD39ARCE1"
}

# Specify the body of the request
data = {
    "engine_name": "Marengo-retrieval-2.6",
    "text": "<YOUR_TEXT>",
}

# Invoke the POST method of the `/embed` endpoint
response = requests.post(EMBED_URL, headers=headers, data=data)

# Print the status code and the response
print(f"Status Code: {response.status_code}")
print("Response:")
print(response.json())

from twelvelabs import TwelveLabs

client = TwelveLabs(api_key="tlk_1D4DWDE37ATK1J2C5MWVD39ARCE1")

res = client.generate.text(
  video_id="6652c6b4d22b3a3c97bef629",
  prompt="I want to generate a description for my video with the following format: Title of the video, followed by a summary in 2-3 sentences, highlighting the main topics."
)
print(f"{res.data}")

# python -m pip install requests

import requests

# Construct the URL of the `/embed` endpoint
BASE_URL = "https://api.twelvelabs.io"
VERSION = "v1.2"
EMBED_URL = f"{BASE_URL}/{VERSION}/embed"

# Set the headers of the request
headers = {
    "x-api-key": "tlk_1D4DWDE37ATK1J2C5MWVD39ARCE1"
}

# Specify the body of the request
data = {
    "engine_name": "Marengo-retrieval-2.6",
    "text": "<YOUR_TEXT>",
}

# Invoke the POST method of the `/embed` endpoint
response = requests.post(EMBED_URL, headers=headers, data=data)

# Print the status code and the response
print(f"Status Code: {response.status_code}")
print("Response:")
print(response.json())